### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by swathigrate** [VikramadityaDev/text_to_image_gen#1]
Hello sir ,
Thanks for great app ....
Actually it's  not working sometimes... Taking time to process to generate image...
Is it generate nfsw content?

![Screenshot_20230424-112821_Arrow Launcher](https://user-images.githubusercontent.com/14991260/233911639-e29a863d-e7b2-4890-a43b-cf74ade45e5c.png)

**Comment by VikramadityaDev** [comment]
As this is a kind of new API [brain fusion], it is going to take some time to produce an HD image.
I'm not sure if it generates NFSW images or not because it's not my API.

**Comment by dj-yacine-flutter** [comment]
> As this is a kind of new API [brain fusion], it is going to take some time to produce an HD image. I'm not sure if it generates NFSW images or not because it's not my API.
 hey dev 
thanks to use my package .
 i notice that the API  was change recently so use the latest version of [https://github.com/dj-yacine-flutter/brain_fusion](brain_fusion) package
