### ISSUE TITLE
its not issue i just want to help you in this amazing app

### ISSUE THREAD

**Issue by Yacine2731** [VikramadityaDev/text_to_image_gen#2]
Hi ,

 I'd like to offer my help to improve your app's performance, remove boilerplate, and fix any functions that may need attention.

I have some experience with flutter and dart , and I believe I could make some valuable contributions to your project. If you're interested, please let me know how I can help.

Thank you, and I look forward to hearing back from you.

Best regards,

**Comment by VikramadityaDev** [comment]
Hey there! 
Thanks for reaching out and offering your help. I really appreciate it! Yes, you can contribute to this project.
