### ISSUE TITLE
Need ui fix

### ISSUE THREAD

**Issue by swathigrate** [VikramadityaDev/text_to_image_gen#6]
Hi developer,
first of all thanks for ui .... Wonderful work you done .. love it

Small suggestion... Need a small button to regenerate images... Hope you solve in next build ....
Thank you very much

**Comment by VikramadityaDev** [comment]
Hi there!

Thank you for your kind words. I'm glad you like the UI. I'll add it to the next build.

**Comment by swathigrate** [comment]
> Hi there!
> 
> Thank you for your kind words. I'm glad you like the UI.
> 
> I'll add it to the next build.
Thanks for reply
Hey another small request....
Is it possible to add bunch facility....at Time 3-4 images,
Thank you

**Comment by Yacine2731** [comment]
> Thanks for reply Hey another small request.... Is it possible to add bunch facility....at Time 3-4 images, Thank you

Thanks for your suggestion . We are working on it
